fragment PageParts on Page {
  __typename
  body
}

fragment PostParts on Post {
  __typename
  title
  excerpt
  date
  author
  featuredImage
  featured
  track
  proof
  cardTitle
  body
}

fragment ProjectParts on Project {
  __typename
  title
  category
  thumbnail
  description
  liveLink
  repoLink
  date
  featured
  track
  proof
  cardTitle
  body
}
